/*
Entity–relationship model:

users
  |
  v
games  <-  game_developers
  |
  v
developers
  |
  v
publishers  <-  game_publishers
  |
  v
platforms
  |
  v
reviews  <-  ratings
  |
  v
wishlist
  |
  v
cart
  |
  v
orders  <-  order_items  <-  shipping_address  <-  payment_methods
  |
  v
game_tags
  |
  v
game_awards
*/

CREATE TABLE USERS (
  ID INT PRIMARY KEY,
  USERNAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE GAMES (
  ID INT PRIMARY KEY,
  TITLE VARCHAR(255) NOT NULL,
  GENRE VARCHAR(255),
  RELEASE_DATE DATE,
  DESCRIPTION TEXT,
  PRICE DECIMAL(10,2) NOT NULL
);

CREATE TABLE DEVELOPERS (
  ID INT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  DESCRIPTION TEXT,
  WEBSITE VARCHAR(255)
);

CREATE TABLE PUBLISHERS (
  ID INT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  DESCRIPTION TEXT,
  WEBSITE VARCHAR(255)
);

CREATE TABLE PLATFORMS (
  ID INT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL
);

CREATE TABLE REVIEWS (
  ID INT PRIMARY KEY,
  USER_ID INT NOT NULL,
  GAME_ID INT NOT NULL,
  REVIEW TEXT,
  FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
  FOREIGN KEY (GAME_ID) REFERENCES GAMES (ID)
);

CREATE TABLE RATINGS (
  ID INT PRIMARY KEY,
  USER_ID INT NOT NULL,
  GAME_ID INT NOT NULL,
  RATING INT NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
  FOREIGN KEY (GAME_ID) REFERENCES GAMES (ID)
);

CREATE TABLE WISHLIST (
  ID INT PRIMARY KEY,
  USER_ID INT NOT NULL,
  GAME_ID INT NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
  FOREIGN KEY (GAME_ID) REFERENCES GAMES (ID)
);

CREATE TABLE CART (
  ID INT PRIMARY KEY,
  USER_ID INT NOT NULL,
  GAME_ID INT NOT NULL,
  QUANTITY INT NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
  FOREIGN KEY (GAME_ID) REFERENCES GAMES (ID)
);

CREATE TABLE ORDERS (
  ID INT PRIMARY KEY,
  USER_ID INT NOT NULL,
  ORDER_DATE DATE NOT NULL,
  TOTAL_AMOUNT DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE TABLE ORDER_ITEMS (
  ID INT PRIMARY KEY,
  ORDER_ID INT NOT NULL,
  GAME_ID INT NOT NULL,
  QUANTITY INT NOT NULL,
  PRICE DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID),
  FOREIGN KEY (GAME_ID) REFERENCES GAMES (ID)
);

CREATE TABLE GAME_PLATFORMS (
  ID INT PRIMARY KEY,
  GAME_ID INT NOT NULL,
  PLATFORM_ID INT NOT NULL,
  FOREIGN KEY (GAME_ID) REFERENCES GAMES (ID),
  FOREIGN KEY (PLATFORM_ID) REFERENCES PLATFORMS (ID)
);

CREATE TABLE GAME_DEVELOPERS (
  ID INT PRIMARY KEY,
  GAME_ID INT NOT NULL,
  DEVELOPER_ID INT NOT NULL,
  FOREIGN KEY (GAME_ID) REFERENCES GAMES (ID),
  FOREIGN KEY (DEVELOPER_ID) REFERENCES DEVELOPERS (ID)
);

CREATE TABLE GAME_PUBLISHERS (
  ID INT PRIMARY KEY,
  GAME_ID INT NOT NULL,
  PUBLISHER_ID INT NOT NULL,
  FOREIGN KEY (GAME_ID) REFERENCES GAMES (ID),
  FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHERS (ID)
);

CREATE TABLE GAME_AWARDS (
  ID INT PRIMARY KEY,
  GAME_ID INT NOT NULL,
  AWARD_NAME VARCHAR(255) NOT NULL,
  YEAR INT NOT NULL,
  FOREIGN KEY (GAME_ID) REFERENCES GAMES (ID)
);